# jenkins base config
jenkins:
  systemMessage: "KernelCI Jenkins configuration\n\n"
  numExecutors: 1
  labelString: ""
  scmCheckoutRetryCount: 0
  mode: NORMAL

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        password: "${ADMIN_PASSWORD}"
security:
  globaljobdslsecurityconfiguration:
    useScriptSecurity: false

# kernelci pipeline library
unclassified:
  globalLibraries:
    libraries:
    - defaultVersion: "${KCI_CORE_BRANCH}"
      name: "kernelci"
      retriever:
        modernSCM:
          scm:
            git:
              remote: "${KCI_CORE_URL}"

  location:
    adminAddress: info@kernelci.org
    url: "${JENKINS_URL}"

# jenkins needs too know git is installed
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
