jobs:
  - script: >
      job('job-dsl') {
        scm {
          git {
            branch('${KCI_JENKINS_BRANCH}')
            remote {
              url('${KCI_JENKINS_URL}')
            }
          }
        }
        triggers {
                scm('H/5 * * * *')
        }
        steps {
          dsl {
            external('jobs.groovy')
            removeAction('DELETE')
          }
        }
      }
