credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "COMPANY LAVA Token"
          id: "lab-company-lava-api"
          scope: GLOBAL
          secret: "${LAVA_COMPANY_TOKEN}"
      - string:
          description: "KernelCI API Upload token"
          id: "api-token"
          scope: GLOBAL
          secret: "${KCI_API_TOKEN}"
